apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: hal
      defaultBucket: power
    secureJsonData:
      token: hal-influxdb-token
    isDefault: true
    editable: true
